import * as path from "path";
import { ensureDir, trackWrite, FSOptions } from "../utils/fs";
import * as process from "node:process";

export type InitTemplate = "next-app" | "fastapi" | "fullstack";

export interface InitProjectOptions {
  template: InitTemplate;
  cwd?: string;
  dryRun?: boolean;
}

export interface InitResult {
  cwd: string;
  template: InitTemplate;
  created: string[];
  skipped: string[];
}

export async function initProject(
  options: InitProjectOptions
): Promise<InitResult> {
  const cwd = options.cwd ?? process.cwd();
  const created: string[] = [];
  const skipped: string[] = [];
  const fsOptions: FSOptions = { dryRun: options.dryRun };

  if (options.template === "next-app") {
    await initNextAppStructure(cwd, created, skipped, fsOptions);
  }

  // Future templates (fastapi, fullstack) can be handled here

  return { cwd, template: options.template, created, skipped };
}

async function initNextAppStructure(
  cwd: string,
  created: string[],
  skipped: string[],
  fsOptions: FSOptions
) {
  // FSD Base Structure + App Router
  const dirsToCreate = [
    "app/(public)",
    "src/app",
    "src/processes",
    "src/pages",
    "src/widgets",
    "src/features",
    "src/entities",
    "src/shared/ui",
    "src/shared/lib",
    "src/shared/config",
  ];

  for (const dir of dirsToCreate) {
    const full = path.join(cwd, dir);
    try {
      await ensureDir(full, fsOptions);
      created.push(dir);
    } catch {
      skipped.push(dir);
    }
  }

  // Generate README.md explain the structure
  await trackWrite(
    cwd,
    "README.fsd.md",
    `# FSD Coach - Base Next.js App Router

This project structure is generated by FSD Coach as a starting point for a Next.js application using the App Router.

## Structure Overview
- app/: Next App Router directory (entrypoints)
- src/app: global providers and initialization.
- src/processes: multi-feature flows (ex: auth-flow)
- src/pages: FSD pages optional (only composition)
- src/widgets: Composite UI blocks (ex: Header, Sidebar)
- src/features: Feature-level modules (ex: login, create-campaign, etc)
- src/entities: Reusable domain models (ex: User, Campaign, Article, etc)
- src/shared: Shared utilities, components, and configurations

## Before You Start
1. Definy your project-specific entities and features.
2. Create features with 'fsd-coach add:feature' command.
3. Keep each decision documented in the generated READMEs.
        `,
    created,
    skipped,
    fsOptions
  );

  // Example feature minimal structure
  await trackWrite(
    cwd,
    "src/features/example/README.md",
    `# Feature: example

Quetions for you to answer before implementing:

- What concrete problem does this feature solve?
- What entities does it use (User, Campaign, etc)?
- What should be exposed in the public API (index.ts)?
- Does this feature depend on another feature? If so, can it break better?
        `,
    created,
    skipped,
    fsOptions
  );

  await trackWrite(
    cwd,
    "src/features/example/index.ts",
    `//Public API for example feature.
// Export only what will make sense for other layers to use.
// Example (after implementing):
// export { ExampleComponent } from "./ui/ExampleComponent";
        `,
    created,
    skipped,
    fsOptions
  );
}
