export const README_FSD_MD = `# {{projectName}} - FSD Architecture

> Next.js application structured with **Feature-Sliced Design**

## 📁 Project Structure

\`\`\`
{{projectName}}/
├── app/                    # Next.js App Router
│   └── (public)/          # Public routes
├── src/
│   ├── app/               # App layer (providers, styles)
│   ├── processes/         # Multi-feature flows
│   ├── pages/             # Page compositions (optional)
│   ├── widgets/           # Composite UI blocks
│   ├── features/          # Business features
│   │   └── example/       # Example feature (remove after)
│   ├── entities/          # Domain entities
│   └── shared/            # Shared code
│       ├── ui/            # UI components
│       ├── lib/           # Utilities
│       ├── api/           # API client
│       └── config/        # Configuration
└── README.fsd.md
\`\`\`

## 🎯 FSD Layers (Bottom to Top)

### 1. Shared
Reusable code **without** business logic.
- UI components (Button, Input)
- Utilities (formatDate, debounce)
- API client configuration

### 2. Entities
Domain models and related logic.
- Types/interfaces (\`User\`, \`Product\`)
- Data transformations
- Presentation components (UserCard)

### 3. Features
User interactions - **one feature = one problem solved**.
- Isolated business logic
- Features DON'T import other features
- Example: \`login\`, \`add-to-cart\`

### 4. Widgets
Composite blocks using features + entities.
- Header (with login + notifications)
- Sidebar (with menu + user info)

### 5. Processes
Multi-feature flows.
- Checkout (cart → shipping → payment)
- Onboarding

### 6. Pages (Optional)
Route-level compositions.
- Can be replaced by Next.js \`app/\` routes

### 7. App
Global providers and initialization.

## 🚀 Next Steps

1. **Remove example:** \`rm -rf src/features/example\`
2. **Create entities:** \`fsd-coach add:entity user\`
3. **Create features:** \`fsd-coach add:feature login\`
4. **Read feature READMEs** before coding!

## 📐 Import Rules

✅ **Allowed:**
- \`features/login\` → \`entities/user\`
- \`widgets/header\` → \`features/login\`
- Any layer → \`shared\`

❌ **Forbidden:**
- \`features/login\` → \`features/logout\` (no cross-feature imports!)
- \`entities/user\` → \`features/login\` (no upward imports)
- \`shared/ui\` → \`features/*\` (shared has no business logic)

## 📚 Resources

- [FSD Official Docs](https://feature-sliced.design)
- [Next.js Documentation](https://nextjs.org/docs)

---

Generated by **FSD Coach** v{{version}} on {{timestamp}}
`;

export const EXAMPLE_FEATURE_README = `# Feature: Example

> ⚠️ **This is an example.** Remove it after creating your own features.

## 📋 Architecture Questionnaire

**Answer BEFORE writing code!**

### 1. What problem does this feature solve?
**Answer:** _This is just an example demonstrating FSD structure._

**Your turn:** _Describe the user problem._

---

### 2. What entities does it use?
**Answer:** None (example only).

**Your turn:** _List entities (User, Product, etc.)_

**Example:**
- ✅ \`User\` - for authentication
- ✅ \`Session\` - to maintain state
- ❌ Don't use other features' entities!

---

### 3. Does it communicate with other features?
**Answer:** No. Features should be isolated.

**Rule:** Features MUST NOT import other features directly.

**Correct approach:**
\`\`\`typescript
// ❌ WRONG
import { logout } from '@/features/logout';

// ✅ CORRECT - via process or widget
const AuthProcess = () => {
  const { LoginButton } = useLogin();
  const { LogoutButton } = useLogout();
  return <>{isAuth ? <LogoutButton /> : <LoginButton />}</>;
};
\`\`\`

---

### 4. What will be exported in Public API (index.ts)?
**Answer:** \`export {}\` (empty example).

**Your turn:** _List exactly what other layers can use._

**Example:**
\`\`\`typescript
// index.ts - Public API
export { LoginForm } from "./ui/LoginForm";
export { useLogin } from "./model/useLogin";
export type { LoginCredentials } from "./model/types";

// DO NOT export:
// - Internal UI components
// - Private helpers
// - Implementation details
\`\`\`

---

## 🏗️ Structure

\`\`\`
example/
├── index.ts           # 🔑 Public API (ONLY entry point)
├── README.md          # 📖 This file
├── ui/                # 🎨 Visual components
├── model/             # 🧠 Business logic + state
├── api/               # 🌐 HTTP calls (optional)
└── lib/               # 🔧 Internal helpers (optional)
\`\`\`

## ✅ Implementation Checklist

- [ ] Define public interface (\`index.ts\`)
- [ ] Implement business logic (\`model/\`)
- [ ] Create UI components (\`ui/\`)
- [ ] Add tests
- [ ] Document usage in README

---

**Tip:** Keep features **focused** on solving ONE problem.
`;
