/**
 * CI/CD integration utilities
 */

import { auditProject } from "../audit/auditor";
import { MetricsCalculator } from "../audit/metrics/calculator";
import { promises as fs } from "fs";
import * as path from "path";

export interface CIOptions {
  projectRoot: string;
  outputDir?: string;
  failOnWarnings?: boolean;
  exportMetrics?: boolean;
  exportFormat?: "json" | "csv" | "markdown";
}

export interface CIResult {
  passed: boolean;
  exitCode: number;
  metricsPath?: string;
  reportPath?: string;
}

/**
 * Run audit in CI/CD environment
 */
export async function runCIAudit(options: CIOptions): Promise<CIResult> {
  const {
    projectRoot,
    outputDir = path.join(projectRoot, ".fsd-reports"),
    failOnWarnings = false,
    exportMetrics = true,
    exportFormat = "json",
  } = options;

  // Ensure output directory exists
  await fs.mkdir(outputDir, { recursive: true });

  // Run audit
  const auditResult = await auditProject({
    cwd: projectRoot,
    strict: failOnWarnings,
  });

  // Generate report
  const reportPath = await generateMarkdownReport(auditResult, outputDir);

  let metricsPath: string | undefined;

  if (exportMetrics) {
    const calculator = new MetricsCalculator();
    const metrics = await calculator.calculate(auditResult, projectRoot);

    if (exportFormat === "json") {
      metricsPath = path.join(outputDir, "metrics.json");
      await calculator.exportToJson(metrics, metricsPath);
    } else if (exportFormat === "csv") {
      metricsPath = path.join(outputDir, "metrics.csv");
      await calculator.exportToCsv(metrics, metricsPath);
    }
  }

  return {
    passed: auditResult.passed,
    exitCode: auditResult.passed ? 0 : 1,
    metricsPath,
    reportPath,
  };
}

/**
 * Generate markdown report for CI
 */
async function generateMarkdownReport(
  auditResult: any,
  outputDir: string
): Promise<string> {
  const reportPath = path.join(outputDir, "audit-report.md");

  const report = `# FSD Coach Audit Report

**Date:** ${new Date().toISOString()}
**Status:** ${auditResult.passed ? "✅ PASSED" : "❌ FAILED"}

## Summary

- **Total Files:** ${auditResult.totalFiles}
- **Errors:** ${auditResult.summary.errors}
- **Warnings:** ${auditResult.summary.warnings}
- **Infos:** ${auditResult.summary.infos}

## Violations

${
  auditResult.violations.length === 0
    ? "_No violations found._"
    : auditResult.violations
        .map(
          (v: any) => `
### ${v.type}

- **File:** \`${v.file}\`
- **Line:** ${v.line || "N/A"}
- **Severity:** ${v.severity}
- **Message:** ${v.message}
${v.suggestion ? `- **Suggestion:** ${v.suggestion}` : ""}
`
        )
        .join("\n")
}

---

Generated by [FSD Coach](https://github.com/k1ngS/fsd-coach)
`;

  await fs.writeFile(reportPath, report, "utf-8");
  return reportPath;
}

/**
 * Generate GitHub Actions annotation format
 */
export function generateGitHubAnnotations(auditResult: any): string {
  return auditResult.violations
    .map((v: any) => {
      const level = v.severity === "error" ? "error" : "warning";
      const file = v.file;
      const line = v.line || 1;

      return `::${level} file=${file},line=${line}::${v.message}`;
    })
    .join("\n");
}

/**
 * Generate GitLab CI format
 */
export function generateGitLabReport(auditResult: any): any {
  return {
    version: "14.0.0",
    vulnerabilities: auditResult.violations.map((v: any, index: number) => ({
      id: `fsd-${index}`,
      category: "sast",
      name: v.type,
      message: v.message,
      description: v.suggestion || v.message,
      severity: v.severity === "error" ? "High" : "Medium",
      location: {
        file: v.file,
        start_line: v.line || 1,
      },
    })),
  };
}
